language: java
jdk:
  - oraclejdk8
dist: trusty
script: "mvn cobertura:cobertura"
after_success:
  - bash <(curl -s https://codecov.io/bash) -t uuid-repo-token
env:
  global:
    - CODECOV_TOKEN=:uuid-repo-token